#!/bin/sh
# clear
if [[ "$OSTYPE" == "msys" ]]; then
  stty cbreak -echo min 0
else
  stty cbreak raw -echo min 0
fi
if [ -f hd.img ]
then
    ./8086tiny bios fd.img hd.img
else
    ./8086tiny bios fd.img
fi
stty cooked echo
